### ISSUE TITLE
To store workflow's in DB

### ISSUE THREAD

**Issue by vkonde** [raoul2000/yii2-workflow#19]
Store status in DB with workflow name and get it..

**Comment by vkonde** [comment]
hi, All status are store in DB now, I am also get in array (using YII array helper) it getting me as follow...

Array
(
    [initialStatusId] => draft
    [status] => Array
        (
            [0] => Array
                (
                    [draft] => Array
                        (
                            [id] => 1
                            [workflow_name] => Visa1
                            [initial] => draft
                            [transition] => assigned,deleted
                        )

                    [assigned] => Array
                        (
                            [id] => 2
                            [workflow_name] => visa1
                            [initial] => assigned
                            [transition] => approval,approve,disapprove,deleted
                        )

                )

        )

)

**Comment by vkonde** [comment]
I don't no is this way is right or wrong....

**Comment by vkonde** [comment]
i have create array as per work flow definition but i get following error.

`"name": "Workflow Validation Exception",
  "message": "One or more end status are not defined : [\n    0 => 'UploadresultWorkflow/deleted'\n    1 => 'UploadresultWorkflow/approval'\n    2 => 'UploadresultWorkflow/approve'\n    3 => 'UploadresultWorkflow/disapprove'\n    4 => 'UploadresultWorkflow/deleted'\n]",`

**Comment by vkonde** [comment]
and this is my getDefinition()..

` public function getDefinition() {
		
		$init = WorkflowTransition::find()
				->where(['workflow_name' => 'visa1'])
				->One();
		$status = WorkflowTransition::find()
				->where(['workflow_name' => 'visa1'])
				->All();
		$defination =  [
					'initialStatusId' => $init->initial,
					'status' => [
						]
			];
		foreach($status as $value)
						{
							
								explode: $thePostIdArray = explode(',', $value->transition);
								$transition['transition'] = $thePostIdArray;
								$defination['status'][$value->initial] = $transition; 
							
						}
						return $defination;
    }`

**Comment by vkonde** [comment]
Done..
Thank you.

**Comment by vkonde** [comment]
```
$status = WorkflowTransition::find()
                ->where(['workflow_name' => 'visa1'])
                ->All();
```
how can make "visa1" (i.e document type changeable ), when user uploading document. can we pass parameter.

**Comment by raoul2000** [comment]
I will reply next week

**Comment by vkonde** [comment]
fine, i have also done with this  document type changeable with session,but still i want to more  discuss with you. 
thnk you.

**Comment by raoul2000** [comment]
Hi vkonde,
I'm back from holidays and try to reply to your question. From what I understand you want to store workflow definition into DB. To do so, you should write a **workflow source** component dedicated to read the workflow from DB, and not from file (like the workflow source component provided with *yii2-workflow*). 

Sometimes ago @feor58 has the same request and I advice you take a look to [this issue](https://github.com/raoul2000/yii2-workflow/issues/13) where we discussed this subject. In this discussion I have proposed an [example of implementation](https://github.com/raoul2000/yii2-workflow/issues/13#issuecomment-137237604) which is incomplete, but can give you an idea on how to implement a **workflowDbSource** component.

bye

**Comment by vkonde** [comment]
yes, i had done in same way [like this](https://github.com/raoul2000/yii2-workflow/issues/13#issuecomment-137237604) get all transitions from DB and return array.

**Comment by vkonde** [comment]
hi,
but my DB structure is different and this is my getDefinition return following array :
i don't know  this is the correct way but it works for me, but yet I am not assigning one workflow for multiple Document type
`public function getDefinition() {
		$workflowname = \yii::$app->session->get('workflowname');
		$init = WorkflowTransition::find()
				->where(['workflow_name' => $workflowname])
				->One();
		$status = WorkflowTransition::find()
				->where(['workflow_name' => $workflowname])
				->All();
		$defination =  [
					'initialStatusId' => $init->initial,
					'status' => [
						]
			];
		foreach($status as $value)
						{							
								explode: $thePostIdArray = explode(',', $value->transition);
								$transition['transition'] = $thePostIdArray;
								$defination['status'][$value->initial] = $transition; 							
						}
		return $defination;	
    }`

**Comment by raoul2000** [comment]
Workflow assignation is done by setting the status to the **initial status of a workflow**. 
If you want to assign a workflow to a Model depending on a model's attribute (the Document *type*) you must implement it (as it is not a built-in feature).

For example : 

```php
if( $model->type == 'TypeA') {
    $model->status = 'workflowA/draft';
} elseif( $model->type == 'TypeB') {
    $model->status = 'workflowB/draft';
} // etc ....
```

**Comment by vkonde** [comment]
hi,
there is another problem in the workflow if i wants to get following,
`$model = UploadResult::find()->all();`
it's give me error because of the workflow model loads after calling UploadResult : 
`public function behaviors()
    {
        return [		
             \raoul2000\workflow\base\SimpleWorkflowBehavior::className()				
        ];
    }`
my workflow definition set if session is set so...
