### ISSUE TITLE
Use foreign key column as attribute

### ISSUE THREAD

**Issue by gdiazderadaa** [raoul2000/yii2-workflow#22]
Hi there!
I was wondering if yii2-workflow supports foregin key column as workfow attribute, cause I'm using a related model to manage statuses dynamically, so instead 'status' col would be 'status_id'

Thanks!

**Comment by raoul2000** [comment]
hi,
you can indeed configure the name of the attribute and replace the default 'status' with 'status_id'. This can be done by using the [statusAttribute](https://github.com/raoul2000/yii2-workflow/blob/master/src/base/SimpleWorkflowBehavior.php#L91) property in the **SimpleWorkflowBehavior** class.

hope this helps !

**Comment by gdiazderadaa** [comment]
Hi, thanks for the answer. Do I need to use then the status_id in the workflow class as well? Cause it'd look less readable...

**Comment by alladas** [comment]
Hi @gdiazderadaa ,
"statusAttribute" is global.
Once set in the behaviors of your model, you are not going to need it in the workflow.

**Comment by maoneid** [comment]
i want to update status. but it is still PostWorkflow/publish on status value during update to database. how to covert status to publish before save to database?

Thanks.

**Comment by maoneid** [comment]
should i use status id converter interface?

**Comment by raoul2000** [comment]
Hi @maoneid,
yes, if you want to handle the status value saved in the db, you should create a **statusIdConverter** class that implements the **IStatusConverter** interface and then initialize the **statusConverter** attribute of the **SimpleWorkflowBehavior** class with it.

You can also use the provided [StatusConverter](http://raoul2000.github.io/yii2-workflow/raoul2000-workflow-base-statusidconverter.html) class which is a map based converter implementation (you can find an example usage in the [unit test section](https://github.com/raoul2000/yii2-workflow/blob/master/tests/codeception/unit/workflow/base/StatusIdConverterTest.php)).

ciao
