### ISSUE TITLE
Call to undefined method ::attach()

### ISSUE THREAD

**Issue by ferllings** [raoul2000/yii2-workflow#26]
Hello,

I was using your workflow plugin with Yii1, and now I'm trying to move on yii2.

I updated my model and Workflow description, but I'm receiving an error:

Call to undefined method app\models\workflows\InternalWorkflow::attach() in /app/vendor/yiisoft/yii2/base/Component.php at line 672

Any idea?

**Comment by ferllings** [comment]
More details,
It works fine if I use the default naming convention: "app\models\swInternal" (My model is Internal)

But if I use "app\models\workflows\InternalWorkflow" I receive the error above.

How should I declare my workflow path in the behaviour ?

**Comment by raoul2000** [comment]
Hi @ferllings 
and sorry for the late reply (I'm on holiday right now :sunglasses:).
To use a custom namespace for your workflows, the simplest solution is to initialise the reserved alias **@workflowDefinitionNamespace** as follows : 

```php
Yii::setAlias('@workflowDefinitionNamespace','app\\models\\workflows');
```

Another option is to declare explicitly the *WorkflowSource* component to use and more important, the class loader component. 
You can find a detailed description in the [Documentation](http://raoul2000.github.io/yii2-workflow/guide-source-file.html#php-class-loader).

ciao

**Comment by ferllings** [comment]
Thanks,

I found another way, adding that in the main.conf

```
        'workflowSource' => [
          'class' => 'raoul2000\workflow\source\file\WorkflowFileSource',
          'definitionLoader' => [
              'class' => 'raoul2000\workflow\source\file\PhpArrayLoader',
              'path'  => '@common/models/workflows'
           ]
        ],
```

Thanks for your hard work, your components is great!!
