### ISSUE TITLE
force model to be a given status

### ISSUE THREAD

**Issue by cornernote** [raoul2000/yii2-workflow#35]
I have a use case where I need to bypass the workflow and directly set the status.  I can't seem to find a method to do this.  Is there any existing way to achieve this?

**Comment by raoul2000** [comment]
You mean assigning directly a status to the status attribute of your model ? If that's the case you should try to call [initStatus()](https://github.com/raoul2000/yii2-workflow/blob/master/src/base/SimpleWorkflowBehavior.php#L325) after status attribute assignment (not tested). Please note that this will not fire any event ...

Let me know

ciao
