### ISSUE TITLE
missing EVENT_*_CHANGE_STATUS when autoInsert is true on ActiveRecord insert

### ISSUE THREAD

**Issue by makroxyz** [raoul2000/yii2-workflow#37]
using autoInsert => true in SimpleWorkflowBehavior  when ActiveRecord is inserted events  EVENT_*_CHANGE_STATUS are not fired.
As described in Generic Events section of the manual I'm expecting the following events:
getStartStatus() == null && getEndStatus() != null : the model is entering into the workflow
getStartStatus() =! null && getEndStatus() != null : the model is changing status
getStartStatus() == null && getEndStatus() == null : the model is leaving into the workflow

It only works when autoInsert is false and I manually sendToStatus() my AR to Initial status ID in beforeSave() function.

**Comment by raoul2000** [comment]
hi @makroxyz,
this is normal as the **autoInsert** feature is not released (not documented neither) and partially implemented.... I'm still not sure it is useful and should be implemented.
