### ISSUE TITLE
Implement constraint for transitions

### ISSUE THREAD

**Issue by PapaStifflera** [raoul2000/yii2-workflow#4]
Implement constraint for transitions as in version for Yii1.

**Comment by raoul2000** [comment]
Status constraint are not available anymore as PHP code declared in the workflow definition. They should now be implemented as event handler attached to a *beforeEnterStatus* event. If the constraint is not satisfied, it must **invalidate** the event so to block the transition.

I will write a chapter on this in the Guide soon....

**Comment by raoul2000** [comment]
check [this chapter](https://github.com/raoul2000/yii2-workflow/blob/master/guide/concept-events.md#status-constraint) for details on how to implement status constraints...
