### ISSUE TITLE
Syntax Error in WorkflowHelper

### ISSUE THREAD

**Issue by Insolita** [raoul2000/yii2-workflow#42]
https://github.com/raoul2000/yii2-workflow/blob/master/src/helpers/WorkflowHelper.php#L153
used ($this->owner) in static method, probably you mean use $model

**Comment by raoul2000** [comment]
Hi @Insolita,
it indeed seems like a big bug !! I'll fix that as soon as possible.
Thanks for the report 😉

**Comment by Insolita** [comment]
Thanks! (it's one of a few methods, not covered with tests  ;-))

**Comment by raoul2000** [comment]
+ simple unit test added
