### ISSUE TITLE
Different namespace and workflow history?

### ISSUE THREAD

**Issue by vitovtnet** [raoul2000/yii2-workflow#46]
1. When I use another namespace

` namespace backend\models`

I get error. (Expected app\models on my PostWorkflow class)

2. Can I see workflow history? When and who changed status?

**Comment by raoul2000** [comment]
1. To use your own namespace (and not rely on the default one) see [this chapter](http://raoul2000.github.io/yii2-workflow/source-file/#changing-the-workflow-definition-class-namespace) from the doc.

2. Workflow history is not a feature provided by yii2-workflow. However that is quite simple to implement by (for example) adding a event handler on the change status Event.

ciao
