### ISSUE TITLE
Question: Is it possible populate a getDefinition method with relations?

### ISSUE THREAD

**Issue by bmsrox** [raoul2000/yii2-workflow#47]

**Comment by raoul2000** [comment]
`getDefinition` must return the workflow as an array (see [Workflow Creation : PHP Source](http://raoul2000.github.io/yii2-workflow/workflow-creation/))

**Comment by bmsrox** [comment]
I am using your extension to other way. i make the getDefinition dynamically

**Comment by raoul2000** [comment]
as long as you return the correct array structure, it should work ok

**Comment by bmsrox** [comment]
Is it possible share this app ?? 
http://raoul2000.good-gamer.net/index.php?r=workflow/status-history/update

**Comment by raoul2000** [comment]
full source code of this site is available at https://github.com/raoul2000/yii2-app
