### ISSUE TITLE
helper function to return all possible statusses?

### ISSUE THREAD

**Issue by mbetel** [raoul2000/yii2-workflow#5]
I'd love to have a helper function returning an Array with all possible statusses from a workflow (not just the reachable ones) to be used in a filter on a grid or otherwise

**Comment by raoul2000** [comment]
Yes, this one is ready to be committed :smile:

**Comment by raoul2000** [comment]
done !

**Comment by cornernote** [comment]
Can you give a bit more detail on how to do this?  I couldn't find anything in the guide.

**Comment by cornernote** [comment]
Found it in another issue, are you able to add this to the guide?

```php
WorkflowHelper::getAllStatusListData(
    $this->model->getWorkflow()->getId(),
    $this->model->getWorkflowSource()
);
```
