### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by dendoy** [raoul2000/yii2-workflow#54]
Cannot use 'Object' as class name as it is reserved

**Comment by raoul2000** [comment]
I'm updating the extension so it can be used with Yii2.0.13 + PHP 7.2. I still need to fixe some tests and I'll release a new version soon.

**Comment by wumahoo** [comment]
Hi，Cannot use 'Object' as class name as it is reserved，7.1 its end of life and is no longer supported.
