### ISSUE TITLE
Playground example

### ISSUE THREAD

**Issue by magestein** [raoul2000/yii2-workflow#56]
Hola @raoul2000 , es posible que puedas subir el ejemplo de [Playground](http://raoul2000.ass-team.fr/index.php?r=workflow/status-history/update) al repositorio? serviría mucho tener de ejemplo directo

----

Eng:
Hi @raoul2000  , is it possible that you can upload the [Playground](http://raoul2000.ass-team.fr/index.php?r=workflow/status-history/update) example  to the repository? it will help to have a direct example

**Comment by raoul2000** [comment]
hola @magestein ... The code for the playground (and actually for all the website) is already available in Github. you can find it [here](https://github.com/raoul2000/yii2-app).
The code for the controller **Workflow Playground** is [here](https://github.com/raoul2000/yii2-app/blob/master/controllers/workflow/StatusHistoryController.php). As it is not dedicated to be shared, the code may not be really clean ... 😎 

Espero que to servira..
