### ISSUE TITLE
keep status updated problem (not an issue, just desperate for your help)

### ISSUE THREAD

**Issue by lindomarcv** [raoul2000/yii2-workflow#57]
Hi, before all thanks for this extension. You did great job.
I am having some problem with the status current id.
Every time i save the model and start the workflow, things goes ok, but when i try the sendToStatus to make a second transition, it doesn't recognize the last initial status and asks for it again.
What i am missing from your guide, here?
Best regards

**Comment by raoul2000** [comment]
Hi @lindomarcv,
Thanks for your nice words 
Just to be sure, did you notice that _sendToStatus_ doesn't save the model, but does perform the transitions ? Did you check [this example](http://raoul2000.github.io/yii2-workflow/special-cookbook/#changing-status) from the documentation ? 

Ok if you did, then I would need a way to reproduce the behavior you are describing. Is it something like : 

```php
$m = new Post();
$m->status = "post/A";
$m->save();

$m->sendToStatus("post/B"); // ERROR here !!
```
_assuming a transition exist between post/A and post/b of course_

Is it what you are experiencing ?
ciao
:sunglasses:

**Comment by lindomarcv** [comment]
Hi, my problem i think was on the initStatus() i was not calling after Find Model. So every time i was trying a transition i was getting a null from the getWorkflowStatus().
Thank U very much for your reply.
Best regards

**Comment by raoul2000** [comment]
Glad to hear you could solve the issue 👍
