### ISSUE TITLE
Migrate to yii3

### ISSUE THREAD

**Issue by philippfrenzel** [raoul2000/yii2-workflow#63]
Hi, as your component is the absolute best for implementing workflows within yii - do you plan to migrate it to yii3 - or maybe you appreciate support for the port? Or maybe I can sponsor you to migrate it (with beer, wine or anything else ;)

**Comment by raoul2000** [comment]
Hi @philippfrenzel, I must say that I didn't follow very closely Yii3 and I would have to eavluate the effort to port yii2-workflow... Do you know when it will be release ? @samdark is targeting a beta release for Spring this year ....

... and by the way thanks for the nice words (I'll go for a bottle of wine 😉). ... and yes, support is always appreciated !
