### ISSUE TITLE
Gridview filter dropdown

### ISSUE THREAD

**Issue by ferllings** [raoul2000/yii2-workflow#65]
Hello,

On my index page, I have a GridView widget, using an ActiveDataProvider object (from ->search() )
So I don't have any model object.
So, I did a bit of 'hack' to get the full list of statues:
```
$model = MyModel::find()->one();
	$allStatuses = WorkflowHelper::getAllStatusListData(
	 	$model->getWorkflow()->getId(),
	 	$model->getWorkflowSource()
	);

GridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'columns'=>[
		[
			'attribute' => 'status',
			'filter' =>$allStatuses,
		]
]
]);


```

Is there a better way to generate the dropdown filter menu that this?

Thanks

**Comment by raoul2000** [comment]
Hi,
given a workflow Id, one option could be to directly get the list of all statuses from the *workflowSource* component (which wouldn't force to read a model from the DB). However this would be possible only if you're sure that `MyModel` is only associated with only one workflow, and that you know the ID of this workflow.
By default the *workflowSource* component has name "**workflowSource**".

Once you have a reference to the **workflowSource** just call [getAllStatuses](http://raoul2000.github.io/yii2-workflow/class-ref/api/class-raoul2000.workflow.source.IWorkflowSource.html#_getAllStatuses) (see [workflowHelper](https://github.com/raoul2000/yii2-workflow/blob/master/src/helpers/WorkflowHelper.php#L70) for example)

Hope it helps

**Comment by ferllings** [comment]
Thanks that works well:

```
	$workflowSource = Yii::$app->get('workflowSource');

	$allStatuses = WorkflowHelper::getAllStatusListData(
	 	'MyWorkflow',
	 	$workflowSource
	);
```
