### ISSUE TITLE
Event on enter workflow

### ISSUE THREAD

**Issue by ferllings** [raoul2000/yii2-workflow#66]
Hello,

I use `SimpleWorkflowBehavior::EVENT_AFTER_CHANGE_STATUS`
To trigger an action when my workflow status changes.

But this event is not triggered when my model enters the workflow using 
```
$model->enterWorkflow();
```

Is there an event that I can use,like
`afterEnterWorkflow{MyWorkflow}`

Thanks

**Comment by raoul2000** [comment]
Hi @ferllings ,
there is indeed an event fired when a model enter a workflow. The Event Model implemented by yii2-workflow is described [here](http://raoul2000.github.io/yii2-workflow/concept-events/#workflow-events). You'll find events like : 
- beforeEnterWorkflow
- beforeEnterStatus
- afterEnterWorkflow
- afterEnterStatus

Above events are fired when a model enters a workflow and so you could attach a handler to the ones that best fit your needs.
Cheers

**Comment by ferllings** [comment]
Thanks,
It's working.

And it looks like I was wrong: 
SimpleWorkflowBehavior::EVENT_AFTER_CHANGE_STATUS is also executed if you enter the workflow.
